// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uvlvjbevnaxvrqyvkxbf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2bHZqYmV2bmF4dnJxeXZreGJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4MDk4ODEsImV4cCI6MjA2MjM4NTg4MX0.75NwUE3V44NArtuiaD-d2Q1d9zBjzc9iz3m7XjGgYGM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);